language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

dist:
  - bionic

addons:
  apt:
    packages:
      - cmake
      - libssl-dev
      - libncurses-dev
      - libetpan-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew bundle; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make

