language:
  - cpp

compiler:
  - clang

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode11
      env:
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl
        - OPENSSL_LIBRARIES=/usr/local/opt/openssl/lib

addons:
  apt:
    packages:
      - libssl-dev
      - libreadline-dev
      - libncurses5-dev
      - libetpan-dev
      - libxapian-dev
      - libsqlite3-dev
  homebrew:
    packages:
      - cmake
      - openssl
      - ncurses
      - libetpan
      - xapian
      - sqlite
    update: true

install:
  # Hack: Get a recent cmake
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.16/cmake-3.16.8-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - cmake --version
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make

