language:
  - cpp

sudo:
  - false

os:
  - linux
#  - osx

dist:
  - xenial

addons:
  apt:
    packages:
      - cmake
      - libssl-dev
      - libncurses-dev
      - libetpan-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew bundle; fi

script:
  - lsb_release -a
  - ls -l /usr/lib/x86_64-linux-gnu/libetpan*
  - ls -l /usr/include/libetpan*
  - mkdir -p build
  - cd build
  - cmake ..
  - make

